<?php

namespace PronoteBundle\Repository;

/**
 * ActivitesScolairesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivitesScolairesRepository extends \Doctrine\ORM\EntityRepository
{
}
