<?php

namespace PronoteBundle\Repository;

/**
 * AnalyticsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnalyticsRepository extends \Doctrine\ORM\EntityRepository
{
}
