<?php

namespace PronoteBundle\Repository;

/**
 * AssiduiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssiduiteRepository extends \Doctrine\ORM\EntityRepository
{
}
