<?php

namespace PronoteBundle\Repository;

/**
 * FautesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FautesRepository extends \Doctrine\ORM\EntityRepository
{
}
