<?php

namespace PronoteBundle\Repository;

/**
 * MenuCantineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuCantineRepository extends \Doctrine\ORM\EntityRepository
{
}
