<?php

namespace PronoteBundle\Repository;

/**
 * NotificationsClasseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationsClasseRepository extends \Doctrine\ORM\EntityRepository
{
    
    
}
