<?php

namespace PronoteBundle\Repository;

/**
 * ObservationsGeneralesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservationsGeneralesRepository extends \Doctrine\ORM\EntityRepository
{
}
