<?php

namespace PronoteBundle\Repository;

/**
 * SeancesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeancesRepository extends \Doctrine\ORM\EntityRepository
{
}
