<?php

namespace PronoteBundle\Repository;

/**
 * TelechargementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TelechargementsRepository extends \Doctrine\ORM\EntityRepository
{
}
